# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemo < Formula
  desc "Memory for AI-assisted development. Search your AI coding sessions."
  homepage "https://github.com/Pilan-AI/mnemo"
  version "1.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.6/mnemo_1.3.6_darwin_amd64.tar.gz"
      sha256 "f2c0f9728ec65f4b0b0a3d64002897ca2cf0b903cc2317a6568f00e5285e08f1"

      def install
        bin.install "mnemo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.6/mnemo_1.3.6_darwin_arm64.tar.gz"
      sha256 "e1b25cfa74ffc260c7b6ff16d47218558bf2ffebc4a6bcf55657f5ff32025ee2"

      def install
        bin.install "mnemo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.6/mnemo_1.3.6_linux_amd64.tar.gz"
      sha256 "e7fcffec20ddf6001e8a056442d572d1904bf40ba9eab8a1e630513af9d2b01c"
      def install
        bin.install "mnemo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.6/mnemo_1.3.6_linux_arm64.tar.gz"
      sha256 "8c9f53925b96891b76849cb38b8bc4a440466845d768b8b1cc08c4be2f59c35d"
      def install
        bin.install "mnemo"
      end
    end
  end

  test do
    system "#{bin}/mnemo", "version"
  end
end
