# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemo < Formula
  desc "Memory for AI-assisted development. Search your AI coding sessions."
  homepage "https://github.com/Pilan-AI/mnemo"
  version "1.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.8/mnemo_1.3.8_darwin_amd64.tar.gz"
      sha256 "204c40ca9ef3006fb6e2c490813410ba7e5c20c50ccbe6dc54cd95a3570e1532"

      def install
        bin.install "mnemo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.8/mnemo_1.3.8_darwin_arm64.tar.gz"
      sha256 "981384c43d371510018c33b7dfaa9873a8b08cec1ec081d58d7ef356376a5ab3"

      def install
        bin.install "mnemo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.8/mnemo_1.3.8_linux_amd64.tar.gz"
      sha256 "53065376d5788149f53e5d99ab9535ce98343b4cb1c8a42679e3d41c45bff5d0"
      def install
        bin.install "mnemo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.8/mnemo_1.3.8_linux_arm64.tar.gz"
      sha256 "7dab23ec470372f1c9b361649c3e1eb122255dd688285637312aeceb010013c6"
      def install
        bin.install "mnemo"
      end
    end
  end

  test do
    system "#{bin}/mnemo", "version"
  end
end
