# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemo < Formula
  desc "Memory for AI-assisted development. Search your AI coding sessions."
  homepage "https://github.com/Pilan-AI/mnemo"
  version "1.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.7/mnemo_1.3.7_darwin_amd64.tar.gz"
      sha256 "88acd3796ac427663d2a05f6e6525e3cf8342d72f0f5e6aea38c9a5628c790ee"

      def install
        bin.install "mnemo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.7/mnemo_1.3.7_darwin_arm64.tar.gz"
      sha256 "cd2878cb991f39eee3657567a21686864bb79ea9faebe8b21972bbccc2a684d8"

      def install
        bin.install "mnemo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.7/mnemo_1.3.7_linux_amd64.tar.gz"
      sha256 "15c924d0928add4098c6e4c30f2405ded95548e2dc8cc0f2a9906e84fd3be6ed"
      def install
        bin.install "mnemo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Pilan-AI/mnemo/releases/download/v1.3.7/mnemo_1.3.7_linux_arm64.tar.gz"
      sha256 "517cf5d3cc71ff9e98058accef45ac2cc522006f9c1bb6e6b3edace4aebe5e8b"
      def install
        bin.install "mnemo"
      end
    end
  end

  test do
    system "#{bin}/mnemo", "version"
  end
end
